### ISSUE TITLE
Site finessing (ensuring design is matched as much as possble)

### ISSUE THREAD

**Issue by rossbruniges** [mozilla/gameon#11]
The current design is rather rough - where backgrounds haven't been included they should be extracted from the Illustrator file and included into the page.

**Comment by rossbruniges** [comment]
Stupidly I started doing some of the homepage stuff and pushed to master - I hope this hasn't cocked up anything that you were working on. I'm sorry :(

**Comment by rossbruniges** [comment]
Another thing to note - we've decided to keep the forms in the way that I've designed them, that additional column was deemed a bit to confusing for users...

**Comment by rossbruniges** [comment]
Equal height cols on the homepage might be an interesting little problem to solve - if a no-JS version is looked into...

**Comment by andrewhayward** [comment]
Short of feedback from Chris's design review, I think this ticket can be closed. Will open up individual tickets for anything that comes from that.
