### ISSUE TITLE
Squezzing in Gallery

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/gameon#110]
We have enough entries to showcase. W00t! Let's find a solution to suqeeze them in the top nav bar.

**Comment by rossbruniges** [comment]
Quick question - where should we put in the new navigation item? First before rules?

**Comment by chloeatplay** [comment]
sounds good  

## 

Chloe Varelidi | @varelidi  
Hackable Games Lead | Mozilla Foundation

https://gameon.mozilla.org (http://www.mozilla.org/en-US/gameon/)
