### ISSUE TITLE
Broken Headline in Game On front page

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/gameon#115]
Is it just me or the new addition has broken the headline? The logo now is not aligned with the top navigation.

**Comment by rossbruniges** [comment]
I think you're probably viewing the site in a smaller screen width than before? To ensure the nav fits and looks good across multiple device widths we have 3 orientations:

Desktop
![desktop](https://f.cloud.github.com/assets/96099/58308/3bff1cca-5b6c-11e2-82d4-6e81dbd6b142.jpg)

Tablet
![tablet](https://f.cloud.github.com/assets/96099/58311/54f047f4-5b6c-11e2-93c7-24f960c14756.jpg)

Mobile
![mobile](https://f.cloud.github.com/assets/96099/58313/654b279a-5b6c-11e2-996e-f2a253ba0da6.jpg)

There was a bug where the nav was on a second line but it was resolved minutes after the IT guy and I noticed it, maybe try clearing your cache?
