### ISSUE TITLE
Text for Site's Home Page between Feb24 - March 8

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/gameon#123]
Between the end of the competition Feb24 and the announcement of winners, roughly March 8 we need some text on the central fold (where the submit button currently stands) that says:

"Submissions for the competition are now closed. Thank you to all who submitted! Play all the games here <link to gallery> and find out who the winners are in March""

**Comment by rossbruniges** [comment]
That's probably better than the "See what people have submitted" that is currently scheduled to appear :)

**Comment by rossbruniges** [comment]
@chloeatplay - in between the challenge closing and the winners being announced the homepage will look like this - https://gameon-dev.mozillalabs.com/

I've added the text you wanted but also noted that the entire bottom section was a bit weird. All the content in the left column was about entering the challenge and as we're judging I guess that we're not going to run that many events.

We can add this back in if you want as we add the winner section in - but for now seemed much easier to just remove. Is that OK for now?

**Comment by rossbruniges** [comment]
@chloeatplay bad news - this isn't going to be deployed until at least Monday.

The good news is the mean time it will say "See what people have submitted" which at least is better then nothing, and doesn't tell users that they should try and submit.
