### ISSUE TITLE
Line spacing sometimes feels cramped

### ISSUE THREAD

**Issue by thornet** [mozilla/gameon#31]
Some pages such as:

https://gameon-dev.mozillalabs.com/en-US/prizes/
https://gameon-dev.mozillalabs.com/en-US/rules/

feel cramped in terms of line-spaces. Maybe some light spacing will help.

Mac OSX 10.7.5.
FF v18.0

**Comment by rossbruniges** [comment]
Hopefully we can clear this one up in the design review

**Comment by andrewhayward** [comment]
We have adjusted this slightly on a global level - did design review have anything to say about it?

**Comment by rossbruniges** [comment]
Nope - I reckon when we next catch here we ask @thornet for her second opinion!

**Comment by ghost** [comment]
Looking better. Closing this thread.
