### ISSUE TITLE
Overlapping categories

### ISSUE THREAD

**Issue by dethe** [mozilla/gameon#34]
How can someone say that their project is Mobile _and_ Hackable, or Hackable _and_ Learning? Checkboxes instead of radio buttons would work, but then the name Categories might need rethinking (or not).

One advantage to using checkboxes is to have a list of features we want to encourage (Learning, Open Source, Open Data, Hackable, Mobile, etc.) and present it so participants are encouraged to have as many of the boxes checked as they can (which doesn't help for categorizing, but can push those goals forward).

As categories, I find these kind of confusing for games anyway. I'd look more towards Adventure, Board, Card, Dice, RPG, Action, Platormer, Strategy as categories for games themselves.

I hope that still counts as one issue.

**Comment by rossbruniges** [comment]
There has been a bit of back and forth on the categories - we did originally have checkboxes after I pointed out the same point as you have done here; but the final word is that we're going with radio buttons and that people can pick only one per submission.

When Chloe is back we might want to discuss this again...

**Comment by rossbruniges** [comment]
Going to close this one out - people are very adamant that it's one category only.
