### ISSUE TITLE
Persona Login, no obvious next step

### ISSUE THREAD

**Issue by dethe** [mozilla/gameon#35]
When I tried to log in, I got what appears to be an incomplete Persona popup[1], not clear how to proceed.

[1] https://www.evernote.com/shard/s5/sh/340a4c55-3f5d-498a-8edc-a71eeed1f280/8938e81cb8d06d83acb708a958c2aea8

**Comment by rossbruniges** [comment]
That's weird - did that happen everytime you tried to login?

Can't reproduce that on any of my machines/browsers - what are you using? Might be a bug in Persona...

**Comment by dethe** [comment]
I'm using Firefox 17.0 on OS X 10.8.2. I'm pretty sure I don't have third-party cookies turned off anymore, but can't remember how to find that setting (checked through Preferences pretty thoroughly).

I only tried logging in a few times, but it happened consistently. I thought it might only happen from certain pages, but I tried from the Apply page, from the Apply page with a submit error, and from the home page. And I just tried again, go the same thing, so it wasn't imagination or a transient issue (I've restarted my browser since then).

Add-ons installed and enabled: Add-on Builder Helper 1.4, Blank Tab Multivariate Test Addon 1.3, BugzillaJS 3.0.4, Firebug 1.10.6, Live HTTP Headers 0.17, Test Pilot 1.2.2. I didn't realize I had most of these until just now, can disable and try again.

Now that I think about it, third-party cookies may be disabled. I was thinking of my work laptop, which was stolen on Friday. I'm back to using my own laptop from 2008, so who knows how it is configured. So I'll try to test that too and get back to you.

**Comment by dethe** [comment]
OK, I've disabled all add-ons, confirmed that third-party cookies are being accepted (they already were), and restarted the browser. I still get the same dialog when I try to log in from Firefox. I get the normal Persona dialog in Chrome, with a field prompting me for my email address.

I had one cookie that matched "persona": 

site: login.persona.org
cookie name: browserid_state
content: [gibberish I can provide if its helpful]
path: /wsapi
Expires on: Xmas

I deleted that and tried again, still no way to log in via Persona in Firefox.

What should I look at next? Firefox is not configured to use a proxy and the OS X firewall is not active. I don't see any network or other errors in the log.

**Comment by rossbruniges** [comment]
I would jump into the persona irc channel because I'm fairly sure this isn't app specific to gameon. Can you log into other personaID sites?

**Comment by dethe** [comment]
That would be #browser_id ? I don't see a #persona in irc.

You're correct though, I can't log in for thimble either.

Moved discussion to Persona issue: https://github.com/mozilla/browserid/issues/2792

**Comment by seanmonstar** [comment]
We're actually hanging out in #identity
