### ISSUE TITLE
Apply text constraints earlier or relax them

### ISSUE THREAD

**Issue by dethe** [mozilla/gameon#36]
Rather than an error page if someone enters too much text in a textarea, either prevent them from entering too much text in the first place (maybe with a counter for how many characters they are still allowed? there are jquery plugins for that [1]) or just allow more text. It's not at all clear why the game description would be limited to 150 characters, especially when the affordances show room for much more than that.

[1] For example: http://roy-jin.appspot.com/jsp/textareaCounter.jsp

**Comment by rossbruniges** [comment]
I have changed this to 1000 chars in one of my waiting branches but yeah, I was looking for a good word counter plugin - have you used that one in the past?

**Comment by dethe** [comment]
I don't know that I've used that one specifically, but I've used similar ones without any problems. That one looks flexible enough to work for us.

**Comment by rossbruniges** [comment]
Hopefully merged in a fix that will make this better (as part of https://github.com/mozilla/gameon/pull/42) - what do you think?

**Comment by rossbruniges** [comment]
@dethe - would you consider this to be closeable now?

**Comment by dethe** [comment]
The count works great, but it is still easy to type too many characters without noticing. Creating a hard limit and preventing more characters from being typed works, but can be annoying when a user is trying to edit down to the limit but can't finish their thought first. Another method is to turn the counter text red when the limit is exceeded. Both the colour and the transition draw the eye, so the user is more likely to notice that they've exceeded the character count.

**Comment by rossbruniges** [comment]
It does turn red though doesn't it?

**Comment by dethe** [comment]
OK, now I see it turn red, but the count is odd. The first number counts up and the second counts down, so I it goes from 0/250 to 250/0 characters rather than from 0/250 to 250/250.

**Comment by rossbruniges** [comment]
Yeah that's bollocks isn't it - am sure at the time it made sense!

**Comment by dethe** [comment]
;-)

**Comment by rossbruniges** [comment]
I've made it better - https://gameon-dev.mozillalabs.com/en-US/apply/ :)

**Comment by dethe** [comment]
Looks great to me, feel free to close it.
