### ISSUE TITLE
Second game submitted didn't show up right away

### ISSUE THREAD

**Issue by dethe** [mozilla/gameon#37]
It showed when I refreshed the page, but you might have a caching issue there.

**Comment by rossbruniges** [comment]
Hmm - we don't use any caching from what I'm aware!!

**Comment by dethe** [comment]
Well, it wasn't anything major. If I see it again I'll let you know.

**Comment by rossbruniges** [comment]
One thing I might do to make this less of a thing - redirect to the single page once an entry has been made rather than the list page :)
