### ISSUE TITLE
Confusing fields

### ISSUE THREAD

**Issue by dethe** [mozilla/gameon#38]
What is the difference between a Game URL and an Online Gameplay URL?

**Comment by rossbruniges** [comment]
This is exactly the kinda of thing I was hoping people would pick up on - thanks :)

**Comment by dethe** [comment]
My pleasure. I try to think what my 12 year old would think if he was submitting one of his games. Actually, I'll try getting him to do that later in the week and let you know what he comes up with.

**Comment by rossbruniges** [comment]
Hopefully merged in a fix that will make this better (as part of https://github.com/mozilla/gameon/pull/42) - what do you think?

**Comment by rossbruniges** [comment]
@dethe - would you consider this to be closeable now?

**Comment by dethe** [comment]
Yes, this is better, thanks!
