### ISSUE TITLE
Game Jam Event listing

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/gameon#43]
Attaching how events should be listed in the left lower bar.

http://www.flickr.com/photos/66772999@N05/8228387170/in/photostream

 In the case we have more than 3 there can be a link that says ...see more

and links to a page in webmaker listing all game jams.\

will we be able to use django to upload these events?

**Comment by rossbruniges** [comment]
There is no functionality on webmaker that can list all of one kind of event. Also, they are being held in the webmaker DB as design jams (I think)

Best we can do is leave it at showing the first 3 (displayed by date)

**Comment by rossbruniges** [comment]
On seconds thoughts - there is no reason why we can't knock up a quick page on gameon showing all the game jams that you put into the system. We'll do that.

**Comment by chloeatplay** [comment]
ok- sounds good. Should I start listing them on web maker then? I know for sure of three happening ^^

**Comment by rossbruniges** [comment]
So this is what we have (events get added manually in the game on admin) - not sure how your screen shot ties in with the functionality asked for, how is this (styling to be fixed).

http://www.flickr.com/photos/thecssdiv/8232731326/in/photostream

**Comment by chloeatplay** [comment]
this is perfect.

**Comment by rossbruniges** [comment]
Cool - the design gets a bit shit though with them in - so we might need to look at that. Equally the newly updated copy might make things look better (it's on the list)

**Comment by chloeatplay** [comment]
solution could be that we update the copy so it's only the events that are listed in that box and after listing three there is a "…see more" link at the bottom to web maker events? will that show all events though? hmm
let's ping chris appleton

**Comment by rossbruniges** [comment]
The ability to add events has been added in https://github.com/mozilla/gameon/pull/58
