### ISSUE TITLE
Colors off on the blue icons

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/gameon#44]
Under the "Build the next generation of web-based games"

they seem to be the wrong shade....

**Comment by rossbruniges** [comment]
Where is this? I can't think of any blue on the site...

**Comment by chloeatplay** [comment]
now it's looking ok- when i checked last time the light blue icons (like the trophy and speech bubbles where off)

**Comment by rossbruniges** [comment]
Awesome - then the bug can be closed!

**Comment by chloeatplay** [comment]
a great moment indeed :)
