### ISSUE TITLE
Missing correct descriptions on submission form

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/gameon#46]
You can submit games in one of three categories: 

1) Best Hackable Game 
Create games that let players remix game mechanics, fork code, or use assets from the web to create their own version. Check out some examples here. 
<link to hackagame.org videocast ready by next Friday 30/11>
2) Best Learning Game
Create games that deepen players' understanding of a concept or help them master a set of skills. Check out some great examples in the "Playmakers" series by our friends at the Institute of Play http://playmakers.instituteofplay.org/
3) Best Cross-Platform Game 
Use the power of mobile phones and other new devices to push the limits of asymetric gaming. This category is searching for games that feel "native" to the platforms they inhabit. World of Goo and Snuggle Truck are two great examples. http://www.worldofgoo.com/  http://snuggletruck.com/

https://gameon-dev.mozillalabs.com/en-US/apply/

**Comment by rossbruniges** [comment]
Good news - these can be changed in the admin section :) I'll show you how when you're online

**Comment by davidascher** [comment]
Asymmetric is misspelled. Also, fyi I don't know what asymmetric gaming
means :-)

**Comment by rossbruniges** [comment]
Another reason why I made it admin editable :)

**Comment by rossbruniges** [comment]
Also requires that the model be changed to allow for larger descriptions

**Comment by rossbruniges** [comment]
Fixed on the dev box - as well as changing 'Cross-Platform Game' to 'Multi Device Games'
