### ISSUE TITLE
Consider using strict mode in JS files

### ISSUE THREAD

**Issue by toolness** [mozilla/gameon#51]
I recommend adding `"use strict";` at the top of [forms.js](https://github.com/mozilla/gameon/blob/master/gameon/base/static/base/js/forms.js) and [site.js](https://github.com/mozilla/gameon/blob/master/gameon/base/static/base/js/site.js) to enable [strict mode](https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Functions_and_function_scope/Strict_mode), as it basically gives you some free automatic error checking on browsers that support it.

**Comment by rossbruniges** [comment]
I've considered this a number of times but this 'Browsers not supporting strict mode will run strict mode code with different behavior from browsers that do' makes my bones shiver...
