### ISSUE TITLE
Update 3rd Category Copy

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/gameon#64]
Title: Multi Device Games
Copy:
Use the power of mobile devices and the web to explore concepts like asymmetric gaming, alternate reality games, and companion apps. This category is searching for games that take place across multiple devices to offer a unique gameplay experience.

**Comment by rossbruniges** [comment]
Worked on in https://github.com/mozilla/gameon/pull/63

**Comment by rossbruniges** [comment]
Fixed on the dev box
