### ISSUE TITLE
Small fixes

### ISSUE THREAD

**Issue by andrewhayward** [mozilla/gameon#80]
- There are a few links to other Mozilla properties that include localisation information in the URL. Make sure this is removed from all of them.
- No closing endif on the profile page if there are no entries
- partnerhip typo
- A little hack to sort out - https://github.com/mozilla/gameon/issues/37
- Adding in a couple of user messages when they do stuff (enter an entry, edit their profile)

**Comment by rossbruniges** [comment]
Pull request merged - with all these fixes in there
