### ISSUE TITLE
Copy Fixes, New Category replacing Learning Category

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/gameon#87]
I am not sure if this is a bug. If not, Let me know how I can upload through admin.

So, shocker - we are changing for the last time one of the categories. Also the copy on the other two needs an update. (no parenthesis like mobileet next to the titles)

1) Best Hackable Game 
Create games that let players remix game mechanics, fork code, or use assets from the web to create their own version (and maybe even learn how to code along the way). 

2) Best Web-Only Game
Create games that can only be played on the web. Get inspired by web-only mechanics such as sharing links and data, finding clues on the web that will help you advance in the game, always-on multi-player, and more—creating the most webilicious game possible!

3) Best Multi-Device Game 
Use the power of  mobile to explore concepts like asymmetric gaming, alternate reality games, and companion apps. This category is searching for games that take advantage of the unique affordances of different platforms they inhabit. 

thanks.
really thanks.
Chloe

**Comment by rossbruniges** [comment]
@chloeatplay I've updated the text at https://gameon-dev.mozillalabs.com/en-US/rules/ - please confirm this is correct?

When we have the REAL live site I'll let you loose on the admin!

**Comment by chloeatplay** [comment]
Prizes Page Copy Update

Best Hackable Game
Awarded to the game with the highest "hackability" score. Hackable Games let their players remix mechanics, fork code or use assets from the web in order for them to create their very own version of an existing game. (and maybe even learn how to code along the way). 

Best Web-Only Game
Awarded to the game that can only be played on the web. Get inspired by web-only mechanics such as sharing links and data, finding clues on the web that will help you advance in the game, always-on multi-player, and more—creating the most webilicious game possible!

Best Multi-Device Game 

Awarded to the game that explores best concepts like asymmetric gaming, alternate reality games, and companion apps. This category is searching for games that take advantage of the unique affordances of different platforms they inhabit.

**Comment by rossbruniges** [comment]
Fixed the text on dev - https://gameon-dev.mozillalabs.com/en-US/prizes/ and updated the fixture to ensure that when we deploy the app to live we don't have to update things ourselves. BUT if we do need to tweak stuff the category description and awards copy are all editable in the DB :)

**Comment by chloeatplay** [comment]
Awarded to the game that pushes the limits of what's possible on the web. Get inspired by web-only mechanics such as sharing links and data, finding clues on the web that will help you advance in the game, always-on multi-player, and more—creating the most webilicious game possible!
