### ISSUE TITLE
Copy Fixes

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/gameon#95]
Rules Page

"You will be to find additional answers in our FAQs." should be

"And you can always find additional info in our FAQs."

Judges Page

Ed Rumley & Katherine Isbister don't have a photo.
If we need photos we can pull from the web
Ed : http://www.chillingo.com/media/articles/images/375x275_ed.jpg
Katherine : http://www.poly.edu/sites/polyproto.poly.edu/files/imagecache/profile_full/pictures/picture-410.jpg

Blog (low priority fixes)

This is silly, but how can I edit my avatar? I can't figure it out under edit your profile in users.
Also, can we have your avatar say Ross and not Game On?
https://blog.mozilla.org/gameon/2012/12/05/gamejams/

**Comment by rossbruniges** [comment]
The copy change I have added in.

The images are on the server, but I believe currently in the wrong place. IT need to run a command to get them to highlight.

The blog - I noticed that too - not sure how to fix that until I work out how to login!
