### ISSUE TITLE
Official GDC requests copy change

### ISSUE THREAD

**Issue by chloeatplay** [mozilla/gameon#99]
Gor an email from the senior marketing manager of GDC, they are requesting the following change in the prizes page, I can't find where to change that in the django admin.

So,

Instead of:
= = =
Get the red carpet treatment! Roundtrip airfare, 7 nights of hotel accomodations in San Francisco, two all-access tickets to GDC 2013 -- which includes entry to the Indie Game Developer Conference -- and more
= = =
We need:
Get the red carpet treatment! Roundtrip airfare, 7 nights of hotel accommodations in San Francisco, two All Access Passes to GDC 2013 -- which includes entry to the Independent Games Summit at Games Developers Conference -- and more

**Comment by rossbruniges** [comment]
Have created a server update bug at https://bugzilla.mozilla.org/show_bug.cgi?id=821689

IT don't like to push stuff to live on Fridays now so this might have to wait until Monday. Comment on the bug if you would like it earlier and they might be kind...

**Comment by rossbruniges** [comment]
It got pushed!
